name: Cypress Tests

on:
  push:
    branches: ["fix-frontend-start"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: |
          cd ./backend
          npm install --frozen-lockfile
      - name: Start backend
        run: |
          cd ./backend
          node app.js &

      - run: node --version

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          start: yarn dev --port 4001 --host 127.0.0.1
          wait-on: 'http://localhost:4000, http://localhost:4001, '
